name: Build Binaries

on:
  push:
    tags:
        - v*
    branches:
      - main
  #workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r PTK/requirements.txt
          pip install pyinstaller

      - name: Build executable with PyInstaller
        run: |
          pyinstaller PTK/PTK_Spec.spec
  
  
  
  release:
    name: Release pushed tag
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latast, ubuntu-latest, windows-latest
    needs: [ build ]
    permissions:
      contents: write
    steps:
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
        run: |
          gh release create "$tag" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${tag#v}" \
              --generate-notes
      - name: Download Windows artifacts
        uses: actions/download-artifact@v4
        with:
          name: build_artifact_windows
      - name: Download Linux artifacts
        uses: actions/download-artifact@v4
        with:
          name: build_artifact_linux
      - name: Download MacOS artifacts
        uses: actions/download-artifact@v4
        with:
          name: build_artifact_macos
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: .
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            **/Producers-Toolkit_*.zip






      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
           name: binaries
           path: dist/*
