# ...existing code...
name: Build and Release Cross-Platform

on:
  push:
    branches:
      - main
    tags:
      - v*
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.12']

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r PTK/requirements.txt
          pip install pyinstaller

      - name: Build (Windows)
        if: matrix.os == 'windows-latest'
        run: |
          pyinstaller --onefile --windowed --name Producers-Toolkit_latest PTK/Producers-Toolkit.py

      - name: Build (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          pyinstaller --onefile --windowed --name Producers-Toolkit_latest PTK/Producers-Toolkit.py

      - name: Build (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          pyinstaller --onefile --name Producers-Toolkit_latest PTK/Producers-Toolkit.py

      - name: Create DMG for macOS
        if: matrix.os == 'macos-latest'
        run: |
          brew install create-dmg
          create-dmg \
            --volname "Producer's Toolkit Installer" \
            --window-pos 200 120 \
            --window-size 800 400 \
            --icon-size 100 \
            --app-drop-link 600 185 \
            "Producer's Toolkit-macOS.dmg" \
            "dist/Producer's-Toolkit.app"

      - name: Create ZIP for Windows
        if: matrix.os == 'windows-latest'
        shell: pwsh
        run: |
          Compress-Archive -Path dist/Producer's Toolkit.exe -DestinationPath Producer's Toolkit-Windows.zip

      - name: Create TAR.GZ for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          tar -czvf Producers-Toolkit-Linux.tar.gz -C dist Producers-Toolkit

      - name: Upload Windows Artifact
        if: matrix.os == 'windows-latest'
        uses: actions/upload-artifact@v4
        with:
          name: build_artifact_windows
          path: Producer's Toolkit-Windows.zip

      - name: Upload macOS Artifact
        if: matrix.os == 'macos-latest'
        uses: actions/upload-artifact@v4
        with:
          name: build_artifact_macos
          path: Producer's Toolkit-macOS.dmg

      - name: Upload Linux Artifact
        if: matrix.os == 'ubuntu-latest'
        uses: actions/upload-artifact@v4
        with:
          name: build_artifact_linux
          path: Producer's Toolkit-Linux.tar.gz

  release:
    name: Release pushed tag
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    needs: [ build ]
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: build_artifact_windows
          path: build_artifact_windows

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: build_artifact_macos
          path: build_artifact_macos

      - name: Download Linux artifact
        uses: actions/download-artifact@v4
        with:
          name: build_artifact_linux
          path: build_artifact_linux

      - name: Display structure of downloaded files
        run: ls -R

      - name: Create GitHub release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Producer's Toolkit Toolkit ${{ github.ref_name }}
          body: |
            ## Downloads
            
            Choose the appropriate file for your operating system:
            
            - **Windows**: Producer's Toolkit-Windows.zip
            - **macOS**: Producer's Toolkit-macOS.dmg
            - **Linux**: Producer's Toolkit-Linux.tar.gz
            
            ## Installation Instructions
            
            ### Windows
            1. Download Producer's Toolkit-Windows.zip
            2. Extract the ZIP file
            3. Run Producer's Toolkit.exe
            
            ### macOS
            1. Download Producer's Toolkit-macOS.dmg
            2. Open the DMG file
            3. Drag Producer's Toolkit Toolkit to your Applications folder
            
            ### Linux
            1. Download Producer's Toolkit-Linux.tar.gz
            2. Extract: `tar -xzvf Producer's Toolkit-Linux.tar.gz`
            3. Run: `./Producer's Toolkit`
          draft: false
          prerelease: false

      - name: Upload Windows Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build_artifact_windows/Producer's Toolkit-Windows.zip
          asset_name: Producer's Toolkit-Windows.zip
          asset_content_type: application/zip

      - name: Upload macOS Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build_artifact_macos/Producer's Toolkit-macOS.dmg
          asset_name: Producer's Toolkit-macOS.dmg
          asset_content_type: application/x-apple-diskimage

      - name: Upload Linux Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build_artifact_linux/Producer's Toolkit-Linux.tar.gz
          asset_name: Producer's Toolkit-Linux.tar.gz
          asset_content_type: application/gzip
      


                 
      

      